### ISSUE TITLE
Manifest limits extension to community edition

### ISSUE THREAD

**Issue by sqlkoala** [zastrowm/vs-NavigateTabGroups#2]
Hi,
the manifest file limits this extension to community edition ( right now), like this:
InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[14.0,)" 

Please add other editions like this (copied from another manifest):
    InstallationTarget Version="[14.0,)" Id="Microsoft.VisualStudio.IntegratedShell" 
    InstallationTarget Version="[14.0,)" Id="Microsoft.VisualStudio.Pro" 
    InstallationTarget Version="[14.0,)" Id="Microsoft.VisualStudio.Enterprise" 

I did this "by hand" and then could install. Thanks for your work,( I came here from stackoverflow where you mentioned it as reply to a request.)

**Comment by zastrowm** [comment]
Thanks!  Version 1.2.1 should have this fix.
