### ISSUE TITLE
Having a floating document window that is Snapped to the left side of the monitor screen renders that document skipped completely when navigating.

### ISSUE THREAD

**Issue by spiralsam** [zastrowm/vs-NavigateTabGroups#5]
If you have a floating document open and use Window Snap feature to place it on the left vertical side of the screen (Win+Left Arrow) (which I assume places its places its upper left corner at precisely (0,0)), then this window will be ignored when you execute the various navigation actions. Also, you must have your Windows taskbar positioned so that it doesn't interfere with that specific position, such as placed at the bottom of the screen where it is by default. I tried with it positioned at the top and the bug didn't occur for me. I also tried with the document Snapped to the right, and no issue.

Very strange.

**Comment by zastrowm** [comment]
Yeah, I was wondering when this would come back and bite me, this is related to the way that we filter "active" tabs, specifically by checking that either Top != or Left != 0.  

Relevant code: https://github.com/zastrowm/vs-NavigateTabGroups/blob/master/src/TabGroupJump.cs#L261

It's going to take a bit of effort to find a solution, but your last bug did too :: )
