### ISSUE TITLE
[Request] VS 2019 Support 

### ISSUE THREAD

**Issue by jgh0721** [zastrowm/vs-NavigateTabGroups#8]
i use VS 2019 Preview 3. but this exetnsion doens't work. :-( 

will you be support vs2019?

**Comment by smileyofoz** [comment]
I've just upgraded to 2019 GA and it says the VSIX installer says it could not resolve some dependencies and was only prepared to install it on 2017.  Cheers!

**Comment by lomholdt** [comment]
I have created [a PR](https://github.com/zastrowm/vs-NavigateTabGroups/pull/9) to make this work with VS2019. If @zastrowm is still maintaining this repo he should be able to publish it to the Visual Studio Marketplace 👍

**Comment by zastrowm** [comment]
Sorry for the laziness ;).  @lomholdt did the hard work and got it working for VS2019 - thanks @lomholdt.

1.4.0 should now be live on the marketplace, which has support for VS2019
